sudo: false
language: rust
rust: nightly
notifications:
  webhooks: http://build.servo.org:54856/travis

script:
 - cargo test
 - "[ $TRAVIS_RUST_VERSION = nightly ] || cargo test --features unstable"
 - "[ $TRAVIS_RUST_VERSION = nightly ] || cargo test --manifest-path plugin/Cargo.toml"

